### ISSUE TITLE
Install Cenisys??

### ISSUE THREAD

**Issue by Bruno99** [iTXTech/Cenisys#3]
Help me! Install Cenisys in VDS!

**Comment by Bruno99** [comment]
OS Debian

**Comment by ishitatsuyuki** [comment]
Should I note this is Work in Progress?

**Comment by TheDiamondYT1** [comment]
Make it Genisys++ or something sounds better

**Comment by ishitatsuyuki** [comment]
I think Cenisys sounds well.

**Comment by gaoyichuan** [comment]
Cenisys and Genisys are completely different projects. So not anything like Genisys++
